### ISSUE TITLE
An example showing creation of a context packet (perhaps in 

### ISSUE THREAD

**Issue by ccera-astro** [ember91/libvrt#1]
The examples don't show how to create a context packet, perhaps update  write_if_data_simple.c to have it emit a single
  context packet before the data packet?

**Comment by ember91** [comment]
Hi!

It seems like I forgot to add examples for IF context write.

See the newest version (1.1.0, or master) for examples of how to write IF context packets. These are `example/src/write_if_context_simple.c` and `example/src/write_if_context_advanced.c`.

**Comment by ccera-astro** [comment]
Thanks. This was very helpful.
