### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by princeje** [ember91/libvrt#3]
**Describe the bug**
`cmake ..`  returns error `CMake Error at CMakeLists.txt:11 (string): string no output variable specified`

and
`cmake -DCMAKE_BUILD_TYPE=Debug -DTEST=On ..` says "Could not find GTest"

**To Reproduce**
Using Ubuntu 18.04 container

FROM ubuntu:18.04
RUN apt update && apt upgrade
RUN apt install git build-essential gcc cmake 
WORKINGDIR=/root
git clone https://github.com/ember91/libvrt.git
cd ./libvrt

**Expected behavior**
To compile

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 (docker container)
 - Version: master branch

**Comment by ember91** [comment]
Hi!

Thanks for posting.

I guess you mean:
```
FROM ubuntu:18.04
RUN apt update && apt upgrade -y
RUN apt install -y git build-essential gcc cmake
WORKDIR /root
RUN git clone https://github.com/ember91/libvrt.git
RUN cd ./libvrt
```
The first one is a bug, which I've fixed. The second one is because google test framework is required for running tests. Google test is listed as a prerequisite in the readme, so I don't think it's an error.
